#ifndef CSWC_PLTF_BSW_ATMEGA32_CSWC_PLTF_MCU_ATMEGA32_SWC_MDIO_MDIO_CFG_H_
#define CSWC_PLTF_BSW_ATMEGA32_CSWC_PLTF_MCU_ATMEGA32_SWC_MDIO_MDIO_CFG_H_


/* MDIO_DIROUTPUT  MDIO_DIRINPUT */

#define MDIO_PIN0_Dir MDIO_DIROUTPUT
#define MDIO_PIN1_Dir MDIO_DIROUTPUT
#define MDIO_PIN2_Dir MDIO_DIROUTPUT
#define MDIO_PIN3_Dir MDIO_DIROUTPUT
#define MDIO_PIN4_Dir MDIO_DIROUTPUT
#define MDIO_PIN5_Dir MDIO_DIROUTPUT
#define MDIO_PIN6_Dir MDIO_DIROUTPUT
#define MDIO_PIN7_Dir MDIO_DIROUTPUT
#define MDIO_PIN8_Dir MDIO_DIROUTPUT
#define MDIO_PIN9_Dir MDIO_DIROUTPUT
#define MDIO_PIN10_Dir MDIO_DIROUTPUT
#define MDIO_PIN11_Dir MDIO_DIROUTPUT
#define MDIO_PIN12_Dir MDIO_DIROUTPUT
#define MDIO_PIN13_Dir MDIO_DIROUTPUT
#define MDIO_PIN14_Dir MDIO_DIROUTPUT
#define MDIO_PIN15_Dir MDIO_DIROUTPUT
#define MDIO_PIN16_Dir MDIO_DIROUTPUT
#define MDIO_PIN17_Dir MDIO_DIROUTPUT
#define MDIO_PIN18_Dir MDIO_DIROUTPUT
#define MDIO_PIN19_Dir MDIO_DIROUTPUT
#define MDIO_PIN20_Dir MDIO_DIROUTPUT
#define MDIO_PIN21_Dir MDIO_DIROUTPUT
#define MDIO_PIN22_Dir MDIO_DIROUTPUT
#define MDIO_PIN23_Dir MDIO_DIROUTPUT
#define MDIO_PIN24_Dir MDIO_DIROUTPUT
#define MDIO_PIN25_Dir MDIO_DIROUTPUT
#define MDIO_PIN26_Dir MDIO_DIROUTPUT
#define MDIO_PIN27_Dir MDIO_DIROUTPUT
#define MDIO_PIN28_Dir MDIO_DIROUTPUT
#define MDIO_PIN29_Dir MDIO_DIROUTPUT
#define MDIO_PIN30_Dir MDIO_DIROUTPUT
#define MDIO_PIN31_Dir MDIO_DIROUTPUT

/* MDIO_OUTPUTHIGH   MDIO_OUTPUTLOW */

#define MDIO_PIN0_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN1_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN2_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN3_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN4_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN5_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN6_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN7_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN8_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN9_Value  MDIO_OUTPUTHIGH
#define MDIO_PIN10_Value MDIO_OUTPUTHIGH
#define MDIO_PIN11_Value MDIO_OUTPUTHIGH
#define MDIO_PIN12_Value MDIO_OUTPUTHIGH
#define MDIO_PIN13_Value MDIO_OUTPUTHIGH
#define MDIO_PIN14_Value MDIO_OUTPUTHIGH
#define MDIO_PIN15_Value MDIO_OUTPUTHIGH
#define MDIO_PIN16_Value MDIO_OUTPUTHIGH
#define MDIO_PIN17_Value MDIO_OUTPUTHIGH
#define MDIO_PIN18_Value MDIO_OUTPUTHIGH
#define MDIO_PIN19_Value MDIO_OUTPUTHIGH
#define MDIO_PIN20_Value MDIO_OUTPUTHIGH
#define MDIO_PIN21_Value MDIO_OUTPUTHIGH
#define MDIO_PIN22_Value MDIO_OUTPUTHIGH
#define MDIO_PIN23_Value MDIO_OUTPUTHIGH
#define MDIO_PIN24_Value MDIO_OUTPUTHIGH
#define MDIO_PIN25_Value MDIO_OUTPUTHIGH
#define MDIO_PIN26_Value MDIO_OUTPUTHIGH
#define MDIO_PIN27_Value MDIO_OUTPUTHIGH
#define MDIO_PIN28_Value MDIO_OUTPUTHIGH
#define MDIO_PIN29_Value MDIO_OUTPUTHIGH
#define MDIO_PIN30_Value MDIO_OUTPUTHIGH
#define MDIO_PIN31_Value MDIO_OUTPUTHIGH

/* MDIO_INPUTPULLUP    MDIO_INPUTHIGHIMPEDANCE */

#define MDIO_PIN0_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN1_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN2_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN3_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN4_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN5_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN6_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN7_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN8_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN9_Mode  MDIO_INPUTPULLUP
#define MDIO_PIN10_Mode MDIO_INPUTPULLUP
#define MDIO_PIN11_Mode MDIO_INPUTPULLUP
#define MDIO_PIN12_Mode MDIO_INPUTPULLUP
#define MDIO_PIN13_Mode MDIO_INPUTPULLUP
#define MDIO_PIN14_Mode MDIO_INPUTPULLUP
#define MDIO_PIN15_Mode MDIO_INPUTPULLUP
#define MDIO_PIN16_Mode MDIO_INPUTPULLUP
#define MDIO_PIN17_Mode MDIO_INPUTPULLUP
#define MDIO_PIN18_Mode MDIO_INPUTPULLUP
#define MDIO_PIN19_Mode MDIO_INPUTPULLUP
#define MDIO_PIN20_Mode MDIO_INPUTPULLUP
#define MDIO_PIN21_Mode MDIO_INPUTPULLUP
#define MDIO_PIN22_Mode MDIO_INPUTPULLUP
#define MDIO_PIN23_Mode MDIO_INPUTPULLUP
#define MDIO_PIN24_Mode MDIO_INPUTPULLUP
#define MDIO_PIN25_Mode MDIO_INPUTPULLUP
#define MDIO_PIN26_Mode MDIO_INPUTPULLUP
#define MDIO_PIN27_Mode MDIO_INPUTPULLUP
#define MDIO_PIN28_Mode MDIO_INPUTPULLUP
#define MDIO_PIN29_Mode MDIO_INPUTPULLUP
#define MDIO_PIN30_Mode MDIO_INPUTPULLUP
#define MDIO_PIN31_Mode MDIO_INPUTPULLUP



#endif /* CSWC_PLTF_BSW_ATMEGA32_CSWC_PLTF_MCU_ATMEGA32_SWC_MDIO_MDIO_CFG_H_ */
